### Create new user
POST http://127.0.0.1:3030/users
content-type: application/json

{
  "email": "hello@feathersjs.com",
  "password": "supersecret"
}

### Get a token
POST http://127.0.0.1:3030/auth
content-type: application/json

{
  "strategy": "local",
  "email": "admin@local",
  "password": "default"
}


### oAuth callback
GET http://localhost:3030/oauth/github/callback

### github oAuth
GET http://localhost:3030/oauth/github

### google oAuth
GET http://localhost:3030/oauth/google